- name: Add nodejs repository to yum repositories
  become: yes
  yum_repository:
    name: nodejs
    description: nodejs yum repository
    baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
    gpgcheck: no

- name: Install nodejs
  become: yes
  yum: name=nodejs-{{node_version}} state=present