- name: Install nginx
  become: yes
  yum: name=nginx state=present

- name: Change the nginx port
  become: yes
  template:
    src: 'nginx.conf'
    dest: '/etc/nginx/conf.d/default.conf'
  notify: Restart nginx  

- name: Start nginx service
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes